name: run Main.py

on:
  schedule:
    # At 5:00 on every 26th day-of-month. (crontab.guru/#0_5_*/26_*_*)
    - cron: '0 5 */26 * *'
  workflow_dispatch:

jobs:
  runs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ğŸ Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: ğŸ“š Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: ğŸ¤‘ Request Cricket payments
        run: python Main.py
        env:
          VENMO_ACCESS_TOKEN: ${{ secrets.VENMO_ACCESS_TOKEN }}
          DAVIS: ${{ secrets.DAVIS }}
